In [1]:
import numpy as np

# Step 1- Input data

In [3]:
# Collect data
x = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

y = np.array([[0],
             [1],
             [1],
             [0]])

In [4]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [5]:
print(y)

[[0]
 [1]
 [1]
 [0]]


# Step 2 - Build the Model and set Hyperparameters

In [7]:
num_epochs = 60000

Randomly initializing the weights using a normal distribution with low deviation

In [14]:
np.random.seed(0)
w0 = 2 * np.random.random((3,4)) - 1
w1 = 2 * np.random.random((4,1)) - 1

In [15]:
print(w0)

[[ 0.09762701  0.43037873  0.20552675  0.08976637]
 [-0.1526904   0.29178823 -0.12482558  0.783546  ]
 [ 0.92732552 -0.23311696  0.58345008  0.05778984]]


In [16]:
print(w1)

[[ 0.13608912]
 [ 0.85119328]
 [-0.85792788]
 [-0.8257414 ]]


# Step 3 - Train Model

In [17]:
def sigmoid(x, deriv=False):
    if (deriv==True):
        return x*(1-x)
    
    return 1/(1+np.exp(-x))

In [21]:
for j in range(num_epochs):
    # -----------------
    # feed forward
    # -----------------
    l0 = x
    l1 = sigmoid(l0.dot(w0))
    l2 = sigmoid(l1.dot(w1))
    
    # -----------------
    # backpropagation
    # -----------------
    # how much the prediction is wrong?
    l2_error = y - l2
    
    if (j % 10000 == 0):
        print("Error: " + str(np.mean(np.abs(l2_error))))
    
    # in what direction is the target value? (gradient descent)
    l2_delta = l2_error * sigmoid(l2, True)
    
    # how much did each l1 weight contributed to l2 error?
    l1_error = l2_delta.dot(w1.T)
    
    # gradient descent on l1
    l1_delta = l1_error * sigmoid(l1, True)
    
    # update the weights taking into consideration the new direction
    w1 += l1.T.dot(l2_delta)
    w0 += l0.T.dot(l1_delta)

Error: 0.00325257856817
Error: 0.0029921276303
Error: 0.00278425530549
Error: 0.00261347785581
Error: 0.00247000515147
Error: 0.00234730869352


# Step 4 - Predict =)

In [27]:
input = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

# predict data using the updated weights
l0 = input
l1 = sigmoid(l0.dot(w0))
l2 = sigmoid(l1.dot(w1))

print(np.around(l2, 2))

[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]]
